modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved" 

[[mods]]
modId = "flabyss"
version = "${version}"
displayName = "Flaring Abyss"
logoFile="icon.png"
authors="LePichu"
description =  'A Project which aims to expand the Nether further!'

[[dependencies.flabyss]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flabyss]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"